name: build

on: [pull_request]

# if need master branch of UnitTesting
#  env:
#     UNITTESTING_TAG: master

jobs:
  linux:
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    steps:
      - uses: actions/checkout@v1
      - name: Install clang
        run: |
          apt update
          apt install -y clang python-pip
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Setup virtual display
        run: sh -e /etc/init.d/xvfb start
      - name: Install prerequisites
        run: |
          pip3 install --upgrade pip pycodestyle pep257
          pip3 install --upgrade coverage==4.5.4 codecov
          pip3 install --upgrade mkdocs mkdocs-material
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - name: Run tests
        run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests --coverage
      - run: |
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Install prerequisites
        run: |
          pip3 install --upgrade pip pycodestyle pep257
          pip3 install --upgrade coverage==4.5.4 codecov
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          which clang
          export PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests --coverage

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v1
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-10.0
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - run: (new-object net.webclient).DownloadFile("https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.ps1","github.ps1")
      - run: |
          ./github.ps1 "bootstrap" -verbose
          ./github.ps1 "install_package_control" -verbose
          ./github.ps1 "run_tests" -coverage -verbose
