name: build

on: [pull_request]

# if need master branch of UnitTesting
#  env:
#     UNITTESTING_TAG: master

jobs:
  linux:
    needs: install_prerequisites
    runs-on: ubuntu-latest
    container: sublimetext/unittesting
    steps:
      - uses: actions/checkout@v1
      - name: Install prerequisites
        run: |
        apt-get update
        apt-get install python3-pip -y
        pip3 install --upgrade pip pycodestyle pep257
        pip3 install --upgrade coverage==4.5.4 codecov==2.0.15
        pip3 install --upgrade mkdocs mkdocs-material
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          which clang
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests --coverage
      - run: |
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  macos:
    needs: install_prerequisites
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install prerequisites
        run: |
        pip3 install --upgrade pip pycodestyle pep257
        pip3 install --upgrade coverage==4.5.4 codecov==2.0.15
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          export PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests --coverage
      - run: |
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  windows:
    needs: install_prerequisites
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: (new-object net.webclient).DownloadFile("https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.ps1","github.ps1")
      - run: |
          ./github.ps1 "bootstrap" -verbose
          ./github.ps1 "install_package_control" -verbose
          ./github.ps1 "run_tests" -coverage -verbose
      - run: |
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
